### ISSUE TITLE
Allow ES mappings for polymorphic types inside an array

### ISSUE THREAD

**Issue by paulsabou** [busymachines/busymachines-commons#7]
Because ES is a schemaless storage system it is an ideal candidate to store polymorphic types.

**An example situation:**

A domain class _Property_ (ie. a house, a flat, a building) mapped as a Root document can have multiple events nested inside as Nested documents (part of an "events" array). Those nested event's can be mapped on different domain classes : _EventImprovement_, _EventRent_, _EventExpense_ (that maybe extend the same Event trait) and each of them can have a different set of fields. 

Right now we can do this only if all the elements of the array have the same domain class but we cannot distinguish between them if they have different domain classes (ie. the first two are EventImprovement's and the last two EventRent's)

**Problem** : When the "events" ES array is read back into the app, each "event" inside the array must be mapped back to the "right" domain class corresponding to it.  

**Proposed solution** :
We should add an additional "_app_class" ES field/property inside each Root document and Nested document and use this to identify the actual domain class that has to be instantiated when the JSON is converted to a domain class.

**Comment by lorandszakacs** [comment]
Spring clean-up. Abandoning. Busy Machines commons shall rise again from its ashes.
