### ISSUE TITLE
Cascading deletes of child documents

### ISSUE THREAD

**Issue by paulsabou** [busymachines/busymachines-commons#8]
**Problem:**
In some cases a document has several other documents that are related and should be deleted if the parent document is deleted. A good example of this is the relation between Customer and Media (ie. one customer can refer to multiple media's that should be deleted when the customer is deleted).

We have several cases in which one document (ie. Customer) can refer to tens of Media documents through their id's. When the customer document is deleted we would like to also delete the referred Media documents. Doing this manually in the app code is error prone and can involve a good deal of code.

**Proposed solution:**
We could extend the ESMapping with an extra property _ParentOf_ (similar with _Nested_) that indicates that the current document field refers to the document id's of some other mapping and that any DELETE operation on the parent should cascade to the children.

**ES parent/child feature is not good enough**
ES has a parent/child feature which allows to cascade parent delete's to child's deletes.
The problem with the ES parent/child feature is that it is limited : the child type mapping must specifiy the type of the parent. As such it's not possible to have a child type (ie. Media) that can have parents of multiple types (ie. Customer, Employee, etc.).

**Comment by lorandszakacs** [comment]
Spring clean-up. Abandoning. Busy Machines commons shall rise again from its ashes.
